# Site settings
author: Stuart Fleishman
title: 
header-img: img/home-bg.png
email: stuart.a.fleishman@gmail.com
copyright_name: Stuart Fleishman
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  FirstForkMilkyWay

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
